### ISSUE TITLE
Incorrect execSync typing

### ISSUE THREAD

**Issue by varnerac** [sikanhe/reason-node#44] opened 2020-12-28 03:48 UTC
In `ChildProcess`, `execSync` is spec'd to return a `string`. However, it will always return a `Buffer.t`. `execSyncWith` can return a `String` if an `~encoding` is specified like `"utf8"` . Otherwise, it defaults to a `Buffer.t`

For confirmation, see [the types repo](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/child_process.d.ts#L483)

**Comment by austindd** [comment] 2020-12-29 04:01
@varnerac Thanks for bringing this to our attention. This will be fixed in the next release. It turns out that this issue applies to other functions in the module, like `exec` and `execFile`. So this uncovered other bugs as well.

For now, I think the best way to implement this is to remove the `encoding` option, since that can be set on the buffer itself for decoding to a string. This eliminates a lot of complexity caused by the polymorphic return type. This change will apply to all the affected functions.

**Closed as completed** 2020-12-29 18:13 UTC
Labels: bug
